In [2]:
import pandas as pd
import numpy as np
import sklearn 
from sklearn import feature_selection
import matplotlib.pyplot as plt
from sklearn.cluster.hierarchical import AgglomerativeClustering

In [3]:
%%time
#Считываем
fname = r'/Users/dmitri/Documents/ML_Boot Camp/csi_analyze/bs_avg_kpi.csv'
cell_d_columns = ['T_DATE','CELL_LAC_ID', 'ERAB_PS_BLOCKING_RATE_LTE','ERAB_PS_DROP_RATE_LTE','RAB_PS_BLOCKING_RATE_3G',
              'RAB_PS_DROP_RATE_3G','TBF_DROP_RATE_2G']
cell_d = pd.read_csv(fname,';',decimal=',',parse_dates=['T_DATE'],usecols = cell_d_columns)

# Работа с форматом day.month
ar = np.array(cell_d['T_DATE'])
month_ar = []
day_ar = []
for i in range(len(ar)):
    month = ar[i][3:5]
    day = ar[i][0:2]
    month_ar.append(month)
    day_ar.append(day)
    
cell_d['month'] = month_ar
cell_d['day'] = day_ar
cell_d.sort_values(['CELL_LAC_ID','month','day'])

# Чистим пустое

cell_d_nan = cell_d[['ERAB_PS_BLOCKING_RATE_LTE','ERAB_PS_DROP_RATE_LTE','RAB_PS_BLOCKING_RATE_3G',
              'RAB_PS_DROP_RATE_3G','TBF_DROP_RATE_2G']]
cell_d_nan = cell_d_nan.fillna(0)
array = np.array(cell_d_nan)

# Кластеризация сот по интернетам
#model = AgglomerativeClustering(n_clusters=3)
#preds_bad_d_cells = model.fit_predict(array)

CPU times: user 1min 38s, sys: 21.1 s, total: 1min 59s
Wall time: 2min 2s


In [88]:
bad_cells_1 = cell_d['CELL_LAC_ID'].loc[cell_d['ERAB_PS_BLOCKING_RATE_LTE'] > 0.5].values

In [116]:
bad_cells_1.size

484

In [111]:
dataframe_bad_cells = pd.DataFrame(data = bad_cells_1, columns = ['t'])

In [117]:
dataframe_bad_cells.shape

(484, 1)

In [132]:
dataframe_bad_cells['t'].value_counts()[:50].index

Int64Index([211917, 324330, 171491, 149441, 129760, 245143, 354177, 128161,
            137270,  32170, 318358,  66689, 234084,  25466, 144498, 283377,
            288085, 214938, 206874, 274589, 327093, 187257,  31613, 145619,
            338845, 206985,  41086, 190285, 338174,  32511, 104703, 329716,
            110306, 352197, 216570, 258928, 279975, 105882, 122865,  23541,
            122194, 121755, 190835, 308733, 306333, 111353, 190073, 151064,
            315683, 150735],
           dtype='int64')

In [130]:
bad_cells = dataframe_bad_cells['t'].value_counts()[:50]

In [136]:
bad_cells_d1 = bad_cells.index

In [140]:
test = np.array(bad_cells_d1)

In [141]:
test

array([211917, 324330, 171491, 149441, 129760, 245143, 354177, 128161,
       137270,  32170, 318358,  66689, 234084,  25466, 144498, 283377,
       288085, 214938, 206874, 274589, 327093, 187257,  31613, 145619,
       338845, 206985,  41086, 190285, 338174,  32511, 104703, 329716,
       110306, 352197, 216570, 258928, 279975, 105882, 122865,  23541,
       122194, 121755, 190835, 308733, 306333, 111353, 190073, 151064,
       315683, 150735])

In [93]:
np.unique(bad_cells_1)

array([  1476,   3601,   4858,   6404,   8796,  11977,  13782,  16588,
        17918,  18936,  22325,  23541,  25466,  25474,  30561,  31613,
        32170,  32185,  32511,  32958,  39751,  41086,  43797,  44946,
        46390,  47276,  52942,  54113,  55926,  62326,  63010,  65277,
        65371,  66689,  68563,  68596,  68956,  76666,  78324,  79100,
        80843,  87700,  92586,  95928,  97182,  97776,  98433,  99741,
       100173, 100284, 101605, 102133, 102879, 103529, 103614, 104703,
       105570, 105882, 110306, 111353, 111424, 112594, 115938, 118398,
       118727, 119963, 121755, 122194, 122865, 122895, 125730, 128161,
       129760, 131789, 137270, 138991, 139101, 140270, 140355, 140412,
       141366, 143733, 144498, 145619, 147444, 147761, 149441, 150735,
       151064, 154294, 155105, 155548, 159860, 160221, 160381, 162962,
       168978, 171491, 171811, 172156, 172239, 177714, 183851, 185611,
       187257, 189604, 190073, 190285, 190835, 191765, 193858, 195024,
      

In [78]:
print cell_d.loc[cell_d['ERAB_PS_BLOCKING_RATE_LTE'] > 0.5].count()
print cell_d.loc[cell_d['ERAB_PS_DROP_RATE_LTE'] > 0.5].count()
print cell_d.loc[cell_d['RAB_PS_BLOCKING_RATE_3G'] > 0.5].count()
print cell_d.loc[cell_d['RAB_PS_DROP_RATE_3G'] > 0.5].count()
print cell_d.loc[cell_d['TBF_DROP_RATE_2G'] > 0.5].count()
#print cell_d.loc[cell_d.RAB_PS_BLOCKING_RATE_3G == 1].count()
#print cell_d.loc[cell_d.RAB_PS_DROP_RATE_3G == 1].count()
#print cell_d.loc[cell_d.TBF_DROP_RATE_2G == 1].count()

T_DATE                       484
CELL_LAC_ID                  484
ERAB_PS_BLOCKING_RATE_LTE    484
ERAB_PS_DROP_RATE_LTE        190
RAB_PS_BLOCKING_RATE_3G        0
RAB_PS_DROP_RATE_3G            0
TBF_DROP_RATE_2G               0
month                        484
day                          484
dtype: int64
T_DATE                       145
CELL_LAC_ID                  145
ERAB_PS_BLOCKING_RATE_LTE    145
ERAB_PS_DROP_RATE_LTE        145
RAB_PS_BLOCKING_RATE_3G        0
RAB_PS_DROP_RATE_3G            0
TBF_DROP_RATE_2G               0
month                        145
day                          145
dtype: int64
T_DATE                       168
CELL_LAC_ID                  168
ERAB_PS_BLOCKING_RATE_LTE      0
ERAB_PS_DROP_RATE_LTE          0
RAB_PS_BLOCKING_RATE_3G      168
RAB_PS_DROP_RATE_3G          168
TBF_DROP_RATE_2G               0
month                        168
day                          168
dtype: int64
T_DATE                       629
CELL_LAC_ID                  629
ERAB

In [46]:
test = cell_d['ERAB_PS_BLOCKING_RATE_LTE'].value_counts()

In [69]:
test.values[-30:]

array([3661, 3667, 3668, 3671, 3681, 3682, 3688, 3688, 3691, 3691, 3692,
       3694, 3695, 3695, 3699, 3702, 3708, 3714, 3718, 3720, 3720, 3724,
       3730, 3733, 3734, 3746, 3750, 3753, 3767, 3831])

In [63]:
test.values

array([   1,    1,    1, ..., 3753, 3767, 3831])

In [38]:
print cell_d.loc[cell_d.ERAB_PS_BLOCKING_RATE_LTE == 1].count()
print cell_d.loc[cell_d.ERAB_PS_DROP_RATE_LTE == 1].count()
print cell_d.loc[cell_d.RAB_PS_BLOCKING_RATE_3G == 1].count()
print cell_d.loc[cell_d.RAB_PS_DROP_RATE_3G == 1].count()
print cell_d.loc[cell_d.TBF_DROP_RATE_2G == 1].count()


T_DATE                       140
CELL_LAC_ID                  140
ERAB_PS_BLOCKING_RATE_LTE    140
ERAB_PS_DROP_RATE_LTE         15
RAB_PS_BLOCKING_RATE_3G        0
RAB_PS_DROP_RATE_3G            0
TBF_DROP_RATE_2G               0
month                        140
day                          140
dtype: int64
T_DATE                       1
CELL_LAC_ID                  1
ERAB_PS_BLOCKING_RATE_LTE    1
ERAB_PS_DROP_RATE_LTE        1
RAB_PS_BLOCKING_RATE_3G      0
RAB_PS_DROP_RATE_3G          0
TBF_DROP_RATE_2G             0
month                        1
day                          1
dtype: int64
T_DATE                       24
CELL_LAC_ID                  24
ERAB_PS_BLOCKING_RATE_LTE     0
ERAB_PS_DROP_RATE_LTE         0
RAB_PS_BLOCKING_RATE_3G      24
RAB_PS_DROP_RATE_3G          24
TBF_DROP_RATE_2G              0
month                        24
day                          24
dtype: int64
T_DATE                       323
CELL_LAC_ID                  323
ERAB_PS_BLOCKING_RATE_LTE      

In [39]:
cell_d.loc[cell_d.RAB_PS_DROP_RATE_3G == 1]

T_DATE  CELL_LAC_ID  ERAB_PS_BLOCKING_RATE_LTE  \
4364      23.04       150187                        NaN   
421422    16.05        52071                        NaN   
445036    17.05       108465                        NaN   
517074    13.04       282164                        NaN   
521309    30.03       264359                        NaN   
609640    11.03       252630                        NaN   
774664    10.03       215537                        NaN   
799116    20.04       339979                        NaN   
840739    14.04       116960                        NaN   
1021263   08.03       202941                        NaN   
1126871   25.03       291222                        NaN   
1138831   20.03       261487                        NaN   
1216070   15.04        83509                        NaN   
1284272   31.03       197428                        NaN   
1450967   26.04       169198                        NaN   
1451576   26.04       341781                        NaN   
1540764   26.04       306102                        NaN   
1767969   15.05       131455                        NaN   
1781639   05.03        90857                        NaN   
1782740   04.04       276620                        NaN   
1972165   25.03       137637                        NaN   
2104821   10.03        90857                        NaN   
2149048   25.05       307779                        NaN   
2169842   20.05       186590                        NaN   
2337587   22.03       264359                        NaN   
2402752   19.04       251209                        NaN   
2439557   13.04       150187                        NaN   
2460219   09.03       145747                        NaN   
2649151   08.03        86760                        NaN   
2758614   15.04       212011                        NaN   
...         ...          ...                        ...   
21222905  20.05       125960                        NaN   
21307950  12.05       171641                        NaN   
21372103  31.05       171391                        NaN   
21462224  02.03         5034                        NaN   
21490912  04.04       196979                        NaN   
21630525  23.04       339979                        NaN   
21631241  23.04         5034                        NaN   
21855248  21.04       370777                        NaN   
21971228  25.03       280767                        NaN   
22005800  14.03         5034                        NaN   
22040205  11.04         2226                        NaN   
22130486  20.03       251209                        NaN   
22149150  31.05       280244                        NaN   
22163027  17.05       198455                        NaN   
22182078  20.03       159347                        NaN   
22225694  29.04       305495                        NaN   
22257392  31.03       260252                        NaN   
22352258  02.03       152824                        NaN   
22382073  08.04       235991                        NaN   
22464023  14.04       150187                        NaN   
22521989  06.05        30520                        NaN   
22674646  10.04        74965                        NaN   
22678214  20.04        31071                        NaN   
22685000  26.03       140335                        NaN   
22805383  08.03       344194                        NaN   
22854511  08.05       258682                        NaN   
22913614  16.03       284367                        NaN   
23003949  09.03       200459                        NaN   
23006491  19.03       137637                        NaN   
23252637  07.04       111831                        NaN   

          ERAB_PS_DROP_RATE_LTE  RAB_PS_BLOCKING_RATE_3G  RAB_PS_DROP_RATE_3G  \
4364                        NaN                      NaN                  1.0   
421422                      NaN                      NaN                  1.0   
445036                      NaN                      NaN                  1.0   
517074                    

In [17]:
test = cell_d['ERAB_PS_BLOCKING_RATE_LTE'].value_counts()

SyntaxError: invalid syntax (<ipython-input-32-cb63c9bb9716>, line 1)

In [8]:
cell_d.describe()

CELL_LAC_ID  ERAB_PS_BLOCKING_RATE_LTE  ERAB_PS_DROP_RATE_LTE  \
count  2.327449e+07               4.337487e+06           2.576097e+06   
mean   1.858339e+05               2.567151e-03           2.268111e-02   
std    1.072366e+05               1.223416e-02           2.111024e-02   
min    1.000000e+00               0.000000e+00           0.000000e+00   
25%    9.309100e+04               5.470000e-04           9.147000e-03   
50%    1.859510e+05               9.470000e-04           1.687500e-02   
75%    2.785890e+05               1.992000e-03           2.955600e-02   
max    3.715700e+05               1.000000e+00           1.000000e+00   

       RAB_PS_BLOCKING_RATE_3G  RAB_PS_DROP_RATE_3G  TBF_DROP_RATE_2G  
count            242187.000000         1.190195e+07      6.393660e+06  
mean                  0.007382         2.813286e-03      2.775382e-05  
std                   0.029374         9.306697e-03      6.521864e-04  
min                   0.000000         0.000000e+00      0.000000e+00  
25%                   0.000657         1.950000e-04      1.100000e-05  
50%                   0.001712         1.389000e-03      2.000000e-05  
75%                   0.004783         3.337000e-03      3.600000e-05  
max                   1.000000         1.000000e+00      1.000000e+00

In [9]:
cell_d.corr()

CELL_LAC_ID  ERAB_PS_BLOCKING_RATE_LTE  \
CELL_LAC_ID                   1.000000                  -0.001565   
ERAB_PS_BLOCKING_RATE_LTE    -0.001565                   1.000000   
ERAB_PS_DROP_RATE_LTE         0.000911                  -0.052019   
RAB_PS_BLOCKING_RATE_3G      -0.014891                        NaN   
RAB_PS_DROP_RATE_3G           0.001787                  -1.000000   
TBF_DROP_RATE_2G              0.000623                        NaN   

                           ERAB_PS_DROP_RATE_LTE  RAB_PS_BLOCKING_RATE_3G  \
CELL_LAC_ID                             0.000911                -0.014891   
ERAB_PS_BLOCKING_RATE_LTE              -0.052019                      NaN   
ERAB_PS_DROP_RATE_LTE                   1.000000                      NaN   
RAB_PS_BLOCKING_RATE_3G                      NaN                 1.000000   
RAB_PS_DROP_RATE_3G                     1.000000                 0.174984   
TBF_DROP_RATE_2G                             NaN                      NaN   

                           RAB_PS_DROP_RATE_3G  TBF_DROP_RATE_2G  
CELL_LAC_ID                           0.001787          0.000623  
ERAB_PS_BLOCKING_RATE_LTE            -1.000000               NaN  
ERAB_PS_DROP_RATE_LTE                 1.000000               NaN  
RAB_PS_BLOCKING_RATE_3G               0.174984               NaN  
RAB_PS_DROP_RATE_3G                   1.000000               NaN  
TBF_DROP_RATE_2G                           NaN          1.000000

In [5]:
%%time
# Кластеризация сот по интернетам
model = AgglomerativeClustering(n_clusters=3)
preds_bad_d_cells = model.fit(array)

CPU times: user 2.55 s, sys: 285 ms, total: 2.83 s
Wall time: 2.87 s


In [12]:
cell_d_nan_min = cell_d_nan[['ERAB_PS_DROP_RATE_LTE','RAB_PS_DROP_RATE_3G','TBF_DROP_RATE_2G']]
cell_d_nan_min = cell_d_nan['ERAB_PS_DROP_RATE_LTE']

In [4]:
cell_d_nan_min

ERAB_PS_DROP_RATE_LTE  TBF_DROP_RATE_2G
0                    0.006851          0.000000
1                    0.027000          0.000000
2                    0.035126          0.000000
3                    0.029308          0.000000
4                    0.008983          0.000000
5                    0.016665          0.000000
6                    0.019227          0.000000
7                    0.000000          0.000000
8                    0.002790          0.000000
9                    0.011725          0.000000
10                   0.021658          0.000000
11                   0.010319          0.000000
12                   0.000000          0.000000
13                   0.000000          0.000063
14                   0.000000          0.000000
15                   0.000000          0.000000
16                   0.000000          0.000000
17                   0.000000          0.000000
18                   0.000000          0.000000
19                   0.000000          0.000000
20                   0.000000          0.000013
21                   0.000000          0.000018
22                   0.000000          0.000000
23                   0.000000          0.000025
24                   0.000000          0.000000
25                   0.000000          0.000000
26                   0.000000          0.000031
27                   0.000000          0.000000
28                   0.000000          0.000020
29                   0.000000          0.000051
...                       ...               ...
499970               0.000000          0.000000
499971               0.000000          0.000000
499972               0.000000          0.000000
499973               0.000000          0.000000
499974               0.000000          0.000000
499975               0.000000          0.000000
499976               0.000000          0.000000
499977               0.000000          0.000000
499978               0.000000          0.000000
499979               0.000000          0.000000
499980               0.000000          0.000000
499981               0.000000          0.000000
499982               0.000000          0.000000
499983               0.000000          0.000000
499984               0.000000          0.000000
499985               0.000000          0.000000
499986               0.000000          0.000000
499987               0.000000          0.000000
499988               0.000000          0.000000
499989               0.000000          0.000000
499990               0.000000          0.000000
499991               0.000000          0.000000
499992               0.040289          0.000000
499993               0.008343          0.000000
499994               0.034340          0.000000
499995               0.016824          0.000000
499996               0.036509          0.000000
499997               0.052159          0.000000
499998               0.037617          0.000000
499999               0.056537          0.000000

[500000 rows x 2 columns]

In [9]:
array = np.array(cell_d_nan_min)

# Кластеризация сот по интернетам
model = AgglomerativeClustering(n_clusters=2)
preds_bad_d_cells = model.fit_predict(array)

ValueError: Expected 2D array, got 1D array instead:
array=[0.006851 0.027    0.035126 ... 0.052159 0.037617 0.056537].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
preds_bad_d_cells[]

In [18]:
cell_d_nan = cell_d_nan.loc[cell_d_nan.ne(0).all(axis=1)]

In [17]:
cell_d_nan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23274487 entries, 0 to 23274486
Data columns (total 5 columns):
ERAB_PS_BLOCKING_RATE_LTE    float64
ERAB_PS_DROP_RATE_LTE        float64
RAB_PS_BLOCKING_RATE_3G      float64
RAB_PS_DROP_RATE_3G          float64
TBF_DROP_RATE_2G             float64
dtypes: float64(5)
memory usage: 887.9 MB


In [25]:
cell_d_nan.loc[cell_d_nan.ne(0).all(axis=1)]

Empty DataFrame
Columns: [ERAB_PS_BLOCKING_RATE_LTE, ERAB_PS_DROP_RATE_LTE, RAB_PS_BLOCKING_RATE_3G, RAB_PS_DROP_RATE_3G, TBF_DROP_RATE_2G]
Index: []

In [34]:
cell_d_nan.ne(0).all(axis = 1)

False

In [8]:

# Импортируем библиотеки
from scipy.cluster.hierarchy import linkage, dendrogram
import matplotlib.pyplot as plt
import pandas as pd
 
# Создаем датафрейм
seeds_df = pd.read_csv(
'http://qps.ru/jNZUT')
 
# Исключаем информацию об образцах зерна, сохраняем для дальнейшего использования
varieties = list(seeds_df.pop('grain_variety'))
 
# Извлекаем измерения как массив NumPy
samples = seeds_df.values
 
# Реализация иерархической кластеризации при помощи функции linkage
mergings = linkage(samples, method='complete')
 
# Строим дендрограмму, указав параметры удобные для отображения
dendrogram(mergings,
           labels=varieties,
           leaf_rotation=90,
           leaf_font_size=6,
           )
 
plt.show()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 5, saw 2
